config/routes.rb
Rails.application.routes.draw do
  root 'thoughts#index' 
  resources :thoughts, only: [:index, :create] do
    resources :bookmarks, only: [:create], controller: 'bookmarks'
  end
  resources :users, only: %i[create show] do
    resources :followings, only: [:create, :destroy], controller: 'followings'
    resources :bookmarks, only: [:destroy, :index], controller: 'bookmarks'
  end
  get 'sign_up' => 'users#new'
  get 'sign_in'  => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'
  post 'sign_in' => 'sessions#create'
  resources :trends, only: %i[index]
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: ':style/avatar.png'
  has_attached_file :cover_image, styles: { medium: '800x800>', thumb: '100x100>' }, default_url: ':style/cover_img.jpg'

  validates_attachment_content_type :photo, content_type: ['image/jpg', 'image/jpeg', 'image/png']
  validates :username, presence: true, length: { minimum: 2 }, uniqueness: true
  validates :full_name, presence: true, length: { minimum: 6 }

  has_many :followings_as_follower, class_name: 'Following', foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :followings_as_follower, source: :followed, dependent: :destroy

  has_many :followings, foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :followings, source: :follower, dependent: :destroy

  has_many :thoughts, foreign_key: :author_id, class_name: 'Thought', dependent: :destroy

  has_many :bookmarks, dependent: :destroy

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }

  def not_followed
    User.ordered_by_most_recent.reject { |user| followed_users.include?(user) || user == self }
  end

  def bookmarked?(thought)
    bookmarks.to_ary.intersect?(thought.bookmarks.to_ary)
  end

  def get_bookmark(thought)
    bookmarks.to_ary.intersection(thought.bookmarks.to_ary)[0]
  end

  def following?(user)
    return true if followed_users.include?(user)

    false
  end

  def followed_users_and_own_thoughts
    Thought.where(author: (followed_users + [self])).includes(:author)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :set_current_user, only: [:show]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @thoughts = @user.thoughts
    @followers = @user.followers
    @followers_count = @user.followers.count
    @following_count = @user.followed_users.count
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    # if current_user

    @user = User.find(params[:id])
  rescue StandardError => e
    flash[:alert] = e.to_s
    redirect_to root_path
  end

  def set_current_user
    @current_user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :full_name, :photo, :cover_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user
    @user
  end

  def retrieve_image(user = @user)
    user.photo.url(:thumb)
  end

  def follow_or_unfollow_btn
    unless current_user.nil?
      if current_user != user && !following?
        follow_btn
      elsif following?
        following_id = following_id user
        return unfollow_btn following_id
      end
    end
    follow_btn unless current_user == user
  end

  def username
    "@#{user.username}"
  end

  def full_name
    user.full_name.to_s
  end

  def follow_btn
    link_to '+/Follow', user_followings_path(user.id), method: :post, class: ' mt-2 follow btn'
  end

  def unfollow_btn(following_id)
    link_to '-/Unfollow', user_following_path(user.id, following_id), method: :delete, class: ' mt-2 follow btn'
  end

  def followers_and_following_count
    "#{@followers_count} Followers     #{@following_count} Following"
  end

  def followers
    @followers
  end

  def cover_image
    user.cover_image.url(:medium)
  end
end

app/views/users/_followers.html.erb
<% followers.each do |user| %>
  <div class="row">
    <div class="image col-3">
      <%= image_tag(retrieve_image(user), size: 64, alt: user_details(user))%>
    </div>
    <div class="col-9 ml-n2">
      <%= link_to user_details(user), user_path(usr_id(user)), class: "pt-3 pb-3 list-group-item font-weight-bold" %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<% if flash[:notice] %>
  <p class="notice" > <%= flash[:notice] %> </p>
<% end %>
<% if flash[:alert] %>
  <p class="alert"> <%= flash[:alert] %> </p>
<% end %>
<%= form_with(model: user, local: true, html: {multipart: true}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>
  <div>
    <%= form.label :photo, "Choose a profile photo" %><br />
    <%= form.file_field :photo %>
  </div>
  <br>
  <div>
    <%= form.label :cover_image, "Choose a cover image" %><br />
    <%= form.file_field :cover_image %>
  </div>
  <br>
  <br>
  <div class="actions">
    <input type="submit" name="commit" value="Register">
  </div>
<% end %>

app/views/users/_thoughts.html.erb
<% @thoughts.each do |thought| %>
  <div class="row usr-row">
    <div class="image col-5 col-lg-3">
      <%= image_tag(user_or_author_img(thought), size: 64) %>
    </div>
    <div class="card thoughts col-7 col-lg-9">
      <div class="card-body">
        <h5 class="card-title">
          <%= user_or_author_details thought %>
        </h5>
        <p class="card-text">
          <%= thought.text %><br>
          <%= bkmark_btn thought %>
          <%= unbkmark_btn thought %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Full name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.full_name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="mt-5 pt-5 pr-n3 pb-5">
<h5> SIGN UP </h5>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', users_path, class: 'back-link' %>
</div>

app/views/users/show.html.erb
<div class="row mt-5 pt-5 pr-n3 ">
  <div class="col-12 col-lg-9">
    <% if flash[:notice] %>
      <p class="notice" > <%= flash[:notice] %> </p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"> <%= flash[:alert] %> </p>
    <% end %>
    <div class="cover_image" >
      <%= image_tag cover_image, height: 350, class: "w-100" %>
    </div>
    <%= render 'layouts/header' %>
    <%= render 'users/thoughts' %>
  </div>
  <div class="col-12 col-lg-3">
    <div class="d-flex justify-content-between">
      <div class='image pt-4'>
        <%= image_tag(retrieve_image, size: 100, alt: username) %>
      </div>
      <div class="pt-5 follow">
        <%= follow_or_unfollow_btn %>
      </div>
    </div>
    <%= username %><br/>
    <%= full_name %><br/>
    <br/>
    <p>
      <%= followers_and_following_count %>
    </p>
    <ul class="followers list-group pr-0 pt-3">
      <li class="pt-3 pb-3 list-group-item text-uppercase h5">Followers</li>
      <%= render 'followers' %>
    </ul>
  </div>
</div>