config/routes.rb
Rails.application.routes.draw do
  root 'thoughts#index' 
  resources :thoughts, only: [:index, :create] do
    resources :bookmarks, only: [:create], controller: 'bookmarks'
  end
  resources :users, only: %i[create show] do
    resources :followings, only: [:create, :destroy], controller: 'followings'
    resources :bookmarks, only: [:destroy, :index], controller: 'bookmarks'
  end
  get 'sign_up' => 'users#new'
  get 'sign_in'  => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'
  post 'sign_in' => 'sessions#create'
  resources :trends, only: %i[index]
end

app/models/thought.rb
class Thought < ApplicationRecord
  validates :text, presence: true, length: { maximum: 1000,
                                             too_long: '1000 characters in post is the maximum allowed.' }
  belongs_to :author, class_name: 'User'

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }

  has_many :bookmarks, dependent: :destroy
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  include TrendsHelper

  before_action :set_current_user, only: %i[create]
  def index
    @trends = trends

    @thought = Thought.new
    @all_thoughts = Thought.all
    if current_user.nil?
      @thoughts = @all_thoughts
      @who_to_follow = User.all.first(5)
      who_to_follow_detail_not_loggedin
    else
      @thoughts = @current_user.followed_users_and_own_thoughts
      @who_to_follow = @current_user.not_followed
      who_to_follow_detail_loggedin
    end
  end

  def create
    @thought = @current_user.thoughts.build(thought_params)

    if @thought.save
      redirect_to thoughts_url, notice: 'Thought was successfully created.'
    else
      render :new
    end
  end

  private

  def set_thought
    @thought = Thought.find(params[:id])
  end

  def set_current_user
    if current_user.nil?
      session[:previous_url] = request.fullpath
      redirect_to sign_in_path
    else
      @current_user = current_user
    end
  end

  def thought_params
    params.require(:thought).permit(:text, :author_id)
  end

  def who_to_follow_detail_not_loggedin
    @who_to_follow_detail = []
    authors = []
    @thoughts.each do |thought|
      @who_to_follow_detail << thought unless authors.include?(thought.author)
      authors << thought.author unless authors.include?(thought.author)
    end
  end

  def who_to_follow_detail_loggedin
    @who_to_follow_detail = []
    authors = []
    @all_thoughts.each do |thought|
      @who_to_follow_detail << thought if @who_to_follow.include?(thought.author) && !authors.include?(thought.author)
      authors << thought.author unless authors.include?(thought.author)
    end
  end
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
  def thought
    @thought
  end

  def author_details(thought)
    "@#{author(thought).username} #{author(thought).full_name}"
  end
end

app/views/thoughts/_errors.html.erb
<p class="errors">
  <%= "Post could not be saved. #{@thought.errors.full_messages.join('. ')}" %>
</p>

app/views/thoughts/_form.html.erb
<%= form_with(model: thought, local: true) do |form| %>
  <% if thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
        <% thought.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thoughts/_trends.html.erb
<% @trends.each do |trend| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= trend["channel"] %>
      </h5>
      <p class="card-text">
        <%= link_to trend["title"], trend[:link] %>
        <br>
      </p>
    </div>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<div class="row mt-5 pt-5 pr-n3 ">
  <div class="col-12 col-lg-9">
    <% if flash[:notice] %>
      <p class="notice" > <%= flash[:notice] %> </p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"> <%= flash[:alert] %> </p>
    <% end %>
    <%= render 'layouts/header' %>
    <%= form_for(thought) do |form| %>
      <%= form.label :share_an_idea %>
      <%= form.text_field :text, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
      <%= retrieve_errors thought %>
      <br>
      <%= form.submit 'Save', class: 'btn btn-primary' %>
      <br>
      <br>
    <% end %>
    <%= render 'users/thoughts' %>
  </div>
    <div class="col-12 col-lg-3">
    <h5>TRENDS FOR YOU</h5>
    <%= render 'trends' %>
  </div>
  <div class="col-12 col-lg-9">
  <h5>WHO TO FOLLOW</h5>
    <%= render 'layouts/who_to_follow_detail' %>
  </div>
    <div class="col-12 col-lg-3">
    <%= render 'layouts/who_to_follow'%>
  </div>
</div>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @thought.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= @thought.author_id %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>