config/routes.rb
Rails.application.routes.draw do
  root 'thoughts#index' 
  resources :thoughts, only: [:index, :create] do
    resources :bookmarks, only: [:create], controller: 'bookmarks'
  end
  resources :users, only: %i[create show] do
    resources :followings, only: [:create, :destroy], controller: 'followings'
    resources :bookmarks, only: [:destroy, :index], controller: 'bookmarks'
  end
  get 'sign_up' => 'users#new'
  get 'sign_in'  => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'
  post 'sign_in' => 'sessions#create'
  resources :trends, only: %i[index]
end

app/views/layouts/_header.html.erb
  <header class= "second-header d-flex navbar justify-content-between pt-3 mt-3 pl-0">
      <ul class="d-flex align-items-center pl-0 h5">
        <li class="pr-3 pl-n2">
          <%=link_to "THOUGHTS", thoughts_path %>
        </li>
        <li class="pr-3">
          <%= link_to "PHOTOS", root_path, method: :delete %>
        </li>
        <li class="pr-3"><%= link_to "VIDEOS",root_path %></li>
      </ul>
      <div class="right-section">
      </div>
    </header>

app/views/layouts/_logo_star.html.erb
<a href= '/thoughts'><i class="fas fa-star"></i></a>

app/views/layouts/_profile_and_bookmarks.html.erb
<li class='d-inline-flex align-items-center list-group-item item_color'>
<a><i class="fas fa-user pt-2 pr-3"></i></a>
<%= link_to "PROFILE", user_path(current_user.id), class: "item-text" %>
</li>
<li class='d-inline-flex align-items-center list-group-item item_color'>
<a><i class="fas fa-bookmark pt-2 pr-3"></i></a>
<%= link_to "BOOKMARKS", user_bookmarks_path(current_user.id), class: "item-text" %>
</li>

app/views/layouts/_sign_in_options.html.erb
<li><i class="fas fa-user"></i></li>
<li><%= link_to "SIGN UP", sign_up_path, class: 'sign-in-options' %></li>
<li><%= link_to "SIGN IN", sign_in_path, class: 'sign-in-options'  %></li>

app/views/layouts/_thoughtstar_logo.html.erb
<%= link_to ('<i class="fas fa-star"></i>').html_safe, root_path  %>

app/views/layouts/_username_logout.html.erb
<a href= '/thoughts'><i class="fas fa-pencil-alt pr-5 fa-lg nav-icons"></i></a>
<a href= '/thoughts'><i class="fas fa-envelope pr-5 fa-lg nav-icons"></i></a>
<a href= '/trends'><i class="fas fa-search pr-4 fa-lg nav-icons"></i></a>
<div class="dropdown pr-5">
  <button type="button" class="btn btn-primary dropdown-toggle nav-icons" data-toggle="dropdown">
    <i class="fas fa-cog fa-lg"></i>
  </button>
  <ul class="dropdown-menu">
    <li class = "list-group-item  border-top-0">
      <%= link_to current_user.username, user_path(current_user.id) %>
    </li>
    <li class = "list-group-item border border-bottom-0">
      <%= link_to "Logout", sign_out_path, method: :delete %>
    </li>
  </ul>
</div>

app/views/layouts/_who_to_follow.html.erb
<ul class="who-to-follow list-group pr-0 pt-3">
  <li class="d-none d-lg-block pt-3 pb-3 list-group-item text-uppercase h5">Who to follow</li>
  <% @who_to_follow.each do |user| %>
    <div class="row">
      <div class="image col-3">
        <%= image_tag(avatar_url(user), size: 64, alt: user_details(user))%>
      </div>
      <div class="col-9 ml-n2">
        <%= link_to user_details(user), user_path(usr_id(user)), class: "pt-3 pb-3 list-group-item font-weight-bold" %>
      </div>
    </div>
  <% end %>
</ul>

app/views/layouts/_who_to_follow_detail.html.erb
<% @who_to_follow_detail.each do |thought| %>
  <div class="row usr-row">
    <div class="image col-5 col-lg-3">
      <%= image_tag(user_or_author_img(thought), size: 64) %>
    </div>
    <div class="card thoughts col-7 col-lg-9">
      <div class="card-body">
        <h5 class="card-title">
          <%= user_or_author_details thought %>
        </h5>
        <p class="card-text">
          <%= thought.text %><br>
          <%= bkmark_btn thought %>
          <%= unbkmark_btn thought %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter(X) Redesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css', integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.4.1.slim.min.js", integrity:"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js", integrity: "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js", integrity: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", crossorigin: "anonymous"%>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.8.1/css/all.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class='row'>
    <div class="col-md-2 bd-sidebar dark_blue">
      <ul class="text-left list-group pr-0 h5">
        <li class="d-inline-flex align-items-center list-group-item item_color">
          <a><i class="fas fa-home pt-2 pr-3"></i></a>
          <%= link_to "HOME PAGE", root_path, class: "item-text" %>
        </li>
        <%= logged_in_usr %>
        <li class="d-inline-flex align-items-center list-group-item item_color">
          <a><i class="fas fa-hashtag pt-2 pr-3"></i></a>
          <%= link_to "DISCOVER", trends_path, class: "item-text" %>
        </li>
      </ul>
    </div>
    <div class="col-md-10 row d-flex">
      <header class="page-header d-flex align-items-center justify-content-between fixed-top">
        <div class="logo-left logo pl-4 h5">
          <%= logo_options %>
        </div>
        <div class="right-section h5">
          <ul class="d-flex align-items-center pt-4">
            <%= sign_in_and_sign_out %>
          </ul>
        </div>
      </header>
      <main class="col-md-12 pr-n5 mr-n5">
        <%= yield %>
      </main>
      <div>
      </body>
    </html>